openapi: 3.0.3
info:
  title: Verilog OJ Forum API
  description: Verilog在线判题系统论坛管理API
  version: 1.0.0
  contact:
    name: API Support
    email: support@verilog-oj.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境
  - url: https://api.verilog-oj.com/api/v1
    description: 生产环境

# 引用组件定义
components:
  $ref: './models/common.yaml#/components'

paths:
  /forum/posts:
    get:
      tags:
        - 论坛管理
      summary: 获取帖子列表
      security:
        - BearerAuth: []
      x-rbac-permissions: [forum.post.read]
      description: 需要帖子读取权限
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: category
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/forum.yaml#/components/schemas/ForumPostListResponse'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    post:
      tags:
        - 论坛管理
      summary: 创建帖子
      security:
        - BearerAuth: []
      x-rbac-permissions: [forum.post.create]
      description: 需要帖子创建权限
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/forum.yaml#/components/schemas/CreateForumPostRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: './models/forum.yaml#/components/schemas/ForumPostCreateResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '403':
          description: 权限不足 - 需要 forum.post.create 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /forum/posts/{id}:
    get:
      tags:
        - 论坛管理
      summary: 获取帖子详情
      security:
        - BearerAuth: []
      x-rbac-permissions: [forum.post.read]
      description: 需要帖子读取权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/forum.yaml#/components/schemas/ForumPostDetailsResponse'
        '403':
          description: 权限不足 - 需要 forum.post.read 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '404':
          description: 帖子不存在
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    put:
      tags:
        - 论坛管理
      summary: 更新帖子
      security:
        - BearerAuth: []
      x-rbac-require:
        permissions: [forum.edit.own]
        roles: [admin, super_admin]
        operator: "OR"
      description: 需要帖子编辑权限（自己的帖子）或管理员权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/forum.yaml#/components/schemas/UpdateForumPostRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: './models/forum.yaml#/components/schemas/ForumPostUpdateResponse'
        '403':
          description: 权限不足 - 需要 forum.edit.own 权限或管理员角色
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    delete:
      tags:
        - 论坛管理
      summary: 删除帖子
      security:
        - BearerAuth: []
      x-rbac-require:
        permissions: [forum.edit.own]
        roles: [admin, super_admin]
        operator: "OR"
      description: 需要帖子编辑权限（自己的帖子）或管理员权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: './models/forum.yaml#/components/schemas/ForumPostDeleteResponse'
        '403':
          description: 权限不足 - 需要 forum.edit.own 权限或管理员角色
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /forum/posts/{id}/replies:
    get:
      tags:
        - 论坛管理
      summary: 获取帖子回复列表
      security:
        - BearerAuth: []
      x-rbac-permissions: [forum.reply.read]
      description: 需要回复读取权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/forum.yaml#/components/schemas/ForumReplyListResponse'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    post:
      tags:
        - 论坛管理
      summary: 创建回复
      security:
        - BearerAuth: []
      x-rbac-permissions: [forum.reply.create]
      description: 需要回复创建权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/forum.yaml#/components/schemas/CreateForumReplyRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: './models/forum.yaml#/components/schemas/ForumReplyCreateResponse'
        '403':
          description: 权限不足 - 需要 forum.reply.create 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'