openapi: 3.0.3
info:
  title: Verilog OJ API
  description: Verilog在线判题系统API
  version: 1.0.0
  contact:
    name: API Support
    email: support@verilog-oj.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境
  - url: https://api.verilog-oj.com/api/v1
    description: 生产环境

# 引用所有接口定义
paths:
  $ref: './apis/user.yaml#/paths'
  $ref: './apis/submission.yaml#/paths'
  $ref: './apis/problem.yaml#/paths'
  $ref: './apis/news.yaml#/paths'
  $ref: './apis/forum.yaml#/paths'
  $ref: './apis/admin.yaml#/paths'

# 引用所有组件定义
components:
  $ref: './models/common.yaml#/components'