openapi: 3.0.3
info:
  title: Verilog OJ Problem Management API
  description: 题目管理相关API
  version: 1.0.0
  contact:
    name: API Support
    email: support@verilog-oj.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境
  - url: https://api.verilog-oj.com/api/v1
    description: 生产环境

paths:
  /problems:
    get:
      tags:
        - 题目管理
      summary: 获取题目列表
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: difficulty
          in: query
          schema:
            type: string
            enum: [Easy, Medium, Hard]
        - name: category
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemList'

    post:
      tags:
        - 题目管理
      summary: 创建题目
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProblemRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'

  /problems/{id}:
    get:
      tags:
        - 题目管理
      summary: 获取题目详情
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'

  /problems/{id}/testcases:
    get:
      tags:
        - 题目管理
      summary: 获取题目测试用例
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  test_cases:
                    type: array
                    items:
                      $ref: '#/components/schemas/TestCase'

    post:
      tags:
        - 题目管理
      summary: 添加测试用例
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestCase'
      responses:
        '201':
          description: 添加成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestCase'

  /problems/{id}/submissions:
    get:
      tags:
        - 题目管理
      summary: 获取题目提交记录
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionList'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        code:
          type: integer

    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        nickname:
          type: string
        avatar:
          type: string
        school:
          type: string
        student_id:
          type: string
        role:
          type: string
          enum: [student, teacher, admin, super_admin]
        solved:
          type: integer
        submitted:
          type: integer
        rating:
          type: integer
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        last_login_at:
          type: string
          format: date-time

    Problem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        input_desc:
          type: string
        output_desc:
          type: string
        difficulty:
          type: string
          enum: [Easy, Medium, Hard]
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        time_limit:
          type: integer
        memory_limit:
          type: integer
        submit_count:
          type: integer
        accepted_count:
          type: integer
        is_public:
          type: boolean
        author:
          $ref: '#/components/schemas/User'
        created_at:
          type: string
          format: date-time

    ProblemList:
      type: object
      properties:
        problems:
          type: array
          items:
            $ref: '#/components/schemas/Problem'
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer

    CreateProblemRequest:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
        input_desc:
          type: string
        output_desc:
          type: string
        difficulty:
          type: string
          enum: [Easy, Medium, Hard]
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        time_limit:
          type: integer
          default: 1000
        memory_limit:
          type: integer
          default: 128
        test_cases:
          type: array
          items:
            $ref: '#/components/schemas/TestCase'

    TestCase:
      type: object
      properties:
        input:
          type: string
        output:
          type: string
        is_sample:
          type: boolean

    Submission:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        problem:
          $ref: '#/components/schemas/Problem'
        code:
          type: string
        language:
          type: string
        status:
          type: string
        score:
          type: integer
        run_time:
          type: integer
        memory:
          type: integer
        error_message:
          type: string
        passed_tests:
          type: integer
        total_tests:
          type: integer
        created_at:
          type: string
          format: date-time

    SubmissionList:
      type: object
      properties:
        submissions:
          type: array
          items:
            $ref: '#/components/schemas/Submission'
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer