openapi: 3.0.3
info:
  title: Verilog OJ Problem API
  description: Verilog在线判题系统题目管理API
  version: 1.0.0
  contact:
    name: API Support
    email: support@verilog-oj.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境
  - url: https://api.verilog-oj.com/api/v1
    description: 生产环境

# 引用组件定义
components:
  $ref: './models/common.yaml#/components'

paths:
  /problems:
    get:
      tags:
        - 题目管理
      summary: 获取题目列表
      security:
        - BearerAuth: []
      x-rbac-permissions: [problem.list]
      description: 需要题目列表查看权限
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: difficulty
          in: query
          schema:
            type: string
            enum: [Easy, Medium, Hard]
        - name: category
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/problem.yaml#/components/schemas/ProblemListResponse'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    post:
      tags:
        - 题目管理
      summary: 创建题目
      security:
        - BearerAuth: []
      x-rbac-permissions: [problem.create]
      description: 需要题目创建权限
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/problem.yaml#/components/schemas/ProblemCreateRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: './models/problem.yaml#/components/schemas/ProblemCreateResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '403':
          description: 权限不足 - 需要 problem.create 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /problems/{id}:
    get:
      tags:
        - 题目管理
      summary: 获取题目详情
      security:
        - BearerAuth: []
      x-rbac-permissions: [problem.read]
      description: 需要题目读取权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/problem.yaml#/components/schemas/ProblemDetailsResponse'
        '403':
          description: 权限不足 - 需要 problem.read 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '404':
          description: 题目不存在
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    put:
      tags:
        - 题目管理
      summary: 更新题目
      security:
        - BearerAuth: []
      x-rbac-require:
        permissions: [problem.update.own]
        roles: [admin, super_admin]
        operator: "OR"
      description: 需要题目更新权限（自己的题目）或管理员权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/problem.yaml#/components/schemas/ProblemUpdateRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: './models/problem.yaml#/components/schemas/ProblemUpdateResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '403':
          description: 权限不足 - 需要 problem.update.own 权限或管理员角色
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    delete:
      tags:
        - 题目管理
      summary: 删除题目
      security:
        - BearerAuth: []
      x-rbac-require:
        permissions: [problem.delete.own]
        roles: [admin, super_admin]
        operator: "OR"
      description: 需要题目删除权限（自己的题目）或管理员权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: './models/problem.yaml#/components/schemas/ProblemDeleteResponse'
        '403':
          description: 权限不足 - 需要 problem.delete.own 权限或管理员角色
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /problems/{id}/testcases:
    get:
      tags:
        - 题目管理
      summary: 获取题目测试用例
      security:
        - BearerAuth: []
      x-rbac-require:
        permissions: [testcase.read.sample]
        roles: [teacher, admin, super_admin]
        operator: "OR"
      description: 普通用户只能查看样例测试用例，题目作者、教师和管理员可查看所有测试用例
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/problem.yaml#/components/schemas/TestCaseListResponse'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    post:
      tags:
        - 题目管理
      summary: 添加测试用例
      security:
        - BearerAuth: []
      x-rbac-require:
        permissions: [testcase.create]
        roles: [admin, super_admin]
        operator: "OR"
      description: 需要测试用例创建权限或管理员权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/problem.yaml#/components/schemas/TestCaseRequest'
      responses:
        '201':
          description: 添加成功
          content:
            application/json:
              schema:
                $ref: './models/problem.yaml#/components/schemas/TestCaseAddResponse'
        '403':
          description: 权限不足 - 需要 testcase.create 权限或管理员角色
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /problems/{id}/submissions:
    get:
      tags:
        - 题目管理
      summary: 获取题目提交记录
      security:
        - BearerAuth: []
      x-rbac-permissions: [submission.list]
      description: 需要提交列表查看权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/submission.yaml#/components/schemas/SubmissionListResponse'
        '403':
          description: 权限不足 - 需要 submission.list 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'