openapi: 3.0.3
info:
  title: Verilog OJ Submission API
  description: Verilog在线判题系统提交管理API
  version: 1.0.0
  contact:
    name: API Support
    email: support@verilog-oj.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境
  - url: https://api.verilog-oj.com/api/v1
    description: 生产环境

# 引用组件定义
components:
  $ref: './models/common.yaml#/components'

paths:
  /submissions:
    get:
      tags:
        - 提交管理
      summary: 获取提交记录列表
      security:
        - BearerAuth: []
      x-rbac-permissions: [submission.list]
      description: 需要提交列表查看权限
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: user_id
          in: query
          schema:
            type: integer
        - name: problem_id
          in: query
          schema:
            type: integer
        - name: status
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/submission.yaml#/components/schemas/SubmissionListResponse'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    post:
      tags:
        - 提交管理
      summary: 提交代码
      security:
        - BearerAuth: []
      x-rbac-permissions: [submission.create]
      description: 需要代码提交权限
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/submission.yaml#/components/schemas/SubmissionCreateRequest'
      responses:
        '201':
          description: 提交成功
          content:
            application/json:
              schema:
                $ref: './models/submission.yaml#/components/schemas/SubmissionCreateResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '403':
          description: 权限不足 - 需要 submission.create 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /submissions/{id}:
    get:
      tags:
        - 提交管理
      summary: 获取提交详情
      security:
        - BearerAuth: []
      x-rbac-permissions: [submission.read]
      description: 需要提交读取权限
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/submission.yaml#/components/schemas/SubmissionDetailsResponse'
        '403':
          description: 权限不足 - 需要 submission.read 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '404':
          description: 提交记录不存在
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    delete:
      tags:
        - 提交管理
      summary: 删除提交
      security:
        - BearerAuth: []
      x-rbac-permissions: [submission.delete]
      description: 需要提交删除权限（仅管理员）
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: './models/submission.yaml#/components/schemas/SubmissionDeleteResponse'
        '403':
          description: 权限不足 - 需要 submission.delete 权限
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /submissions/user:
    get:
      tags:
        - 提交管理
      summary: 获取用户提交记录
      security:
        - BearerAuth: []
      x-rbac-permissions: [submission.list]
      description: 需要提交列表查看权限（获取当前用户的提交记录）
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/submission.yaml#/components/schemas/SubmissionListResponse'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /submissions/stats:
    get:
      tags:
        - 提交管理
      summary: 获取提交统计
      security:
        - BearerAuth: []
      x-rbac-permissions: [submission.read]
      description: 需要提交读取权限（获取统计信息）
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/submission.yaml#/components/schemas/SubmissionStatsResponse'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'