openapi: 3.0.3
info:
  title: Verilog OJ User API
  description: Verilog在线判题系统用户管理API
  version: 1.0.0
  contact:
    name: API Support
    email: support@verilog-oj.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境
  - url: https://api.verilog-oj.com/api/v1
    description: 生产环境

# 引用组件定义
components:
  $ref: './models/common.yaml#/components'

paths:
  /users/register:
    post:
      tags:
        - 用户管理
      summary: 用户注册
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/user.yaml#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: './models/user.yaml#/components/schemas/RegisterResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /users/login:
    post:
      tags:
        - 用户管理
      summary: 用户登录
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/user.yaml#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: './models/user.yaml#/components/schemas/LoginResponse'
        '401':
          description: 用户名或密码错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /users/profile:
    get:
      tags:
        - 用户管理
      summary: 获取个人信息
      security:
        - BearerAuth: []
      x-rbac-permissions: [user.profile.read]
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: './models/user.yaml#/components/schemas/UserProfileResponse'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

    put:
      tags:
        - 用户管理
      summary: 更新个人信息
      security:
        - BearerAuth: []
      x-rbac-permissions: [user.profile.update]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/user.yaml#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: './models/user.yaml#/components/schemas/UpdateProfileResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'

  /users/password:
    put:
      tags:
        - 用户管理
      summary: 修改密码
      security:
        - BearerAuth: []
      x-rbac-permissions: [user.password.change]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/user.yaml#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: 密码修改成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '401':
          description: 原密码错误
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'
        '403':
          description: 权限不足
          content:
            application/json:
              schema:
                $ref: './models/common.yaml#/components/schemas/Error'