openapi: 3.0.3
info:
  title: Verilog OJ Submission Management API
  description: 提交管理相关API
  version: 1.0.0
  contact:
    name: API Support
    email: support@verilog-oj.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境
  - url: https://api.verilog-oj.com/api/v1
    description: 生产环境

paths:
  /submissions:
    get:
      tags:
        - 提交管理
      summary: 获取提交记录列表
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: user_id
          in: query
          schema:
            type: integer
        - name: problem_id
          in: query
          schema:
            type: integer
        - name: status
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionListResponse'

    post:
      tags:
        - 提交管理
      summary: 提交代码
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmissionCreateRequest'
      responses:
        '201':
          description: 提交成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionCreateResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /submissions/{id}:
    get:
      tags:
        - 提交管理
      summary: 获取提交详情
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionDetailsResponse'
        '404':
          description: 提交记录不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - 提交管理
      summary: 删除提交
      description: 仅管理员可删除提交记录
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionDeleteResponse'
        '403':
          description: 需要管理员权限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /submissions/user:
    get:
      tags:
        - 提交管理
      summary: 获取用户提交记录
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionListResponse'

  /submissions/stats:
    get:
      tags:
        - 提交管理
      summary: 获取提交统计
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionStatsResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

    Submission:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        problem_id:
          type: integer
        code:
          type: string
        language:
          type: string
        status:
          type: string
        score:
          type: integer
        error_message:
          type: string
        passed_tests:
          type: integer
        total_tests:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    SubmissionListResponse:
      type: object
      properties:
        submissions:
          type: array
          items:
            $ref: '#/components/schemas/Submission'
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer

    SubmissionCreateRequest:
      type: object
      required:
        - problem_id
        - code
      properties:
        problem_id:
          type: integer
        code:
          type: string
        language:
          type: string

    SubmissionCreateResponse:
      type: object
      properties:
        message:
          type: string
        submission:
          $ref: '#/components/schemas/Submission'

    SubmissionDetailsResponse:
      type: object
      properties:
        submission:
          $ref: '#/components/schemas/Submission'

    SubmissionDeleteResponse:
      type: object
      properties:
        message:
          type: string

    SubmissionStats:
      type: object
      properties:
        total_submissions:
          type: integer
        accepted_submissions:
          type: integer
        solved_problems:
          type: integer
        acceptance_rate:
          type: number
          format: float

    SubmissionStatsResponse:
      type: object
      properties:
        stats:
          $ref: '#/components/schemas/SubmissionStats'
