name: Backend Coverage Check

on:
  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=mod
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod

      - name: Download dependencies
        run: go mod download

      - name: Static analysis
        run: make vet

      - name: Run coverage check
        run: make coverage-check

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.txt
