name: Backend Coverage Check

on:
  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=mod
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod

      - name: Download dependencies
        run: go mod download

      - name: Install tooling
        run: |
          go install github.com/google/wire/cmd/wire@v0.6.0
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2

      - name: Verify Wire generated code
        run: make wire-check

      - name: Static analysis
        run: make vet

      - name: Run lint
        run: make lint

      - name: Run coverage check
        run: make coverage-check

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.txt

      - name: Clean coverage artifacts
        if: always()
        run: rm -f coverage.out coverage.txt
